include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false

linter:
  rules:
    package_api_docs: true
    # public_member_api_docs: true
    constant_identifier_names: false