name: suncalc
description: A port of the suncalc library from https://github.com/mourner/suncalc
version: 0.1.0


environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.15.7


