name: dart_suncalc
description: A dart port of the suncalc library from https://github.com/mourner/suncalc
version: 0.1.0
author: Soroosh Pezeshki
homepage: https://github.com/Soroosh



environment:
  sdk: ">=2.12.2 <3.0.0"

dev_dependencies:
  test: ^1.16.5
