name: dart_suncalc
description: A dart port of the suncalc library from https://github.com/mourner/suncalc
version: 0.2.1
homepage: https://github.com/Soroosh



environment:
  sdk: ">=2.13.3 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.8
